#ifndef BROKENLINE_H
#define BROKENLINE_H

#include <vector>

#include "point.h"

namespace geometry {
struct BrokenLine {
  explicit BrokenLine(const std::vector<Point>& points) : points(points) {}
  virtual double CalculatePerimeter() const;

  virtual ~BrokenLine() = default;

  // generated by default
  //  BrokenLine(const BrokenLine& constuct_from) { points =
  //  constuct_from.points; } BrokenLine& operator=(const BrokenLine& right_arg)
  //  {
  //    points = right_arg.points;
  //    return *this;
  //  }

 protected:
  std::vector<Point> points;
};
}  // namespace geometry

#endif  // BROKENLINE_H
